//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMYPE_API2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManoDeObra
    {
        public int ID_ManoDeObra { get; set; }
        public string NombreMO { get; set; }
        public string TipoD_I { get; set; }
        public decimal Salario { get; set; }
        public string PeriodoSalario { get; set; }
        public int TiempoU_Producida { get; set; }
        public string PeriodoTiempo { get; set; }
        public Nullable<int> FK_ID_Producto { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
