//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMYPE_API2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales
    {
        public int ID_Material { get; set; }
        public string Descripcion { get; set; }
        public string TipoD_I { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int U_Producidas { get; set; }
        public int FK_ID_Producto { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
